version: "3.7"
services:
  mysql:
    container_name: mysql-jakartaee
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bvtech
      MYSQL_USER: bvtech
      MYSQL_PASSWORD: bvtech
    ports:
      - 3306:3306
  wildfly:
    container_name: wildfly-container
    build: ./
    environment:
      - MYSQL_URI=mysql:3306
    ports:
      - 8080:8080
    depends_on:
      - mysql

volumes:
  mysql-data:
    name: mysql-data

networks:
  default:
    name: bvtech
    driver: bridge
