version: "3.7"
services:
  bvtech-mysql:
    container_name: bvtech-mysql
    build: ../bvtech-mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
  bvtech-jakartaee:
    container_name: bvtech-jakartaee
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - bvtech-mysql
    environment:
      - WAIT_HOSTS=bvtech-mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

volumes:
  mysql-data:
    name: mysql-data

networks:
  default:
    name: bvtech
    driver: bridge
