server:
  port: 8081

spring:
  application:
    name: bvtech-gateway
  cloud:
    gateway:
      routes:
      - id: analyzerModule
        uri: http://bvtech-springboot-analyzer:8083/
        predicates:
        - Path=/betvictor/text/**
      - id: dbModule
        uri: http://bvtech-springboot-db:8082/
        predicates:
        - Path=/betvictor/history/**
