version: 2
jobs:
  build:
    docker:
      - image: mosonyi15/jakarta-wildfly:0.2

    working_directory: ~/repo

    environment:
      # JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "jakartaee/pom.xml" }}
            - v1-dependencies-{{ checksum "springboot/bvtech-analyzer/pom.xml" }}
            - v1-dependencies-{{ checksum "springboot/bvtech-db/pom.xml" }}
            - v1-dependencies-{{ checksum "springboot/bvtech-gateway/pom.xml" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cd jakartaee && mvn dependency:go-offline && cd ..
      - run: cd springboot/bvtech-analyzer && mvn dependency:go-offline && cd ../..
      - run: cd springboot/bvtech-db && mvn dependency:go-offline && cd ../..
      - run: cd springboot/bvtech-gateway && mvn dependency:go-offline && cd ../..

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies

      # Build project and run tests
      - run: cd jakartaee && mvn verify && cd ..
      - run: cd springboot/bvtech-analyzer && mvn verify && cd ../..
      - run: cd springboot/bvtech-db && mvn verify && cd ../..
      - run: cd springboot/bvtech-gateway && mvn verify && cd ../..

      # Store artifacts
      - store_artifacts:
          path: jakartaee/target/bvtech-jakartaee.war
      - store_artifacts:
          path: springboot/bvtech-analyzer/target/bvtech-analyzer.jar
      - store_artifacts:
          path: springboot/bvtech-db/target/bvtech-db.jar
      - store_artifacts:
          path: springboot/bvtech-gateway/target/bvtech-gateway.jar

      # Store test results
      - store_test_results:
          path: jakartaee/target/site
      #- store_test_results:
      #    path: springboot/bvtech-analyzer/target/site
      #- store_test_results:
      #    path: springboot/bvtech-db/target/site
      #- store_test_results:
      #    path: springboot/bvtech-gateway/target/site
