version: 2
jobs:
  build-bvtech-jakartaee:
    docker:
      - image: maven:latest

    working_directory: ~/repo

    environment:
      # JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "bvtech-jakartaee/pom.xml" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Change to project directory
      - run: cd bvtech-jakartaee
      
      # Pull dependencies
      - run: mvn dependency:go-offline

      # Store dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies

      # Build project and run tests
      - run: mvn clean verify

      # Store artifacts
      - store_artifacts:
          path: bvtech-jakartaee/target/bvtech-jakartaee.war

      # Store test results
      - store_test_results:
          path: bvtech-jakartaee/target/site

  build-bvtech-springboot-analyzer:
    docker:
      - image: maven:latest

    working_directory: ~/repo

    environment:
      # JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "bvtech-springboot/bvtech-analyzer/pom.xml" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Change to project directory
      - run: cd bvtech-springboot/bvtech-analyzer
      
      # Pull dependencies
      - run: mvn dependency:go-offline

      # Store dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies

      # Build project and run tests
      - run: mvn clean verify

      # Store artifacts
      - store_artifacts:
          path: bvtech-springboot/bvtech-analyzer/target/bvtech-springboot-analyzer.war
